# Deploy site to GitHub pages with SASS
name: Pages Deploy

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Build Sass
        uses: gha-utilities/sass-build@v0.4.9
        with:
          source: ./index.scss
          destination: ./index.css
          sourceMap: true
      -
        name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          build_dir: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
